server:
  port: 8888

mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_spike?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    name: spike
    type: com.alibaba.druid.pool.DruidDataSource


